import Footer from "@/components/Footer"
import Header from "@/components/Header"
import Search from "@/components/Search"
import Sidebar from "@/components/Sidebar"
import { SearchProvider } from "@/context/Search"
import { SidebarProvider } from "@/context/Sidebar"
import "./globals.css"

export const metadata = {
    title: "The Movie DB Clone",
    description: "Generated by create next app",
}

const RootLayout = ({ children }) => (
    <html lang="en">
        <body className="text-white">
            <SearchProvider>
            <SidebarProvider>
                <Header />
                <Search />
                <Sidebar />
                <main> 
                    {children}
                </main>
                <Footer />
            </SidebarProvider>
            </SearchProvider>
        </body>
    </html>
)

export default RootLayout