import Footer from "@/components/Footer"
import Header from "@/components/Header"
import Search from "@/components/Search"
import Sidebar from "@/components/Sidebar"
import { SearchProvider } from "@/context/Search"
import { SidebarProvider } from "@/context/Sidebar"
import "./globals.css"

import { Source_Sans_3 } from "next/font/google"
const font = Source_Sans_3({ subsets: ["latin"] })

export const metadata = {
    title: "The Movie DB Clone",
    description: "Generated by create next app",
}

const RootLayout = ({ children }) => (
    <html lang="en" className={font.className}>
        <body className="text-white">
            <SearchProvider>
            <SidebarProvider>
                <Header />
                <Search />
                <Sidebar />
                <main className="max-w-[1300px] xl:m-auto"> 
                    {children}
                </main>
                <Footer />
            </SidebarProvider>
            </SearchProvider>
        </body>
    </html>
)

export default RootLayout